### ISSUE TITLE
Output token limit

### ISSUE THREAD

**Issue by mgralikowski** [kargnas/laravel-ai-translator#9]
My translation process often fails and I've noticed that the most likely reason is the exceeded output token limit.

The error:
![image](https://github.com/user-attachments/assets/a64e248c-0aa7-470b-9025-699767bc5058)

 (I debugged and AI functions returned just an empty array):
![image](https://github.com/user-attachments/assets/42b48330-b929-49f6-975d-a98e99b2761b)

is general and doesn't give any value. It would be great to catch exceptions and return something more specific. In this case, the solution is to reduce the batch size.

By the way, the default value of `retries` (3) generates unnecessary extra costs in this specific case.

**Comment by kargnas** [comment]
I refactored the code a little while ago. So errors like this shouldn't happen as often anymore.
The three retries are still significant. Since this uses AI, the results are unpredictable, so we'll keep the 3 retries. We also added a config that allows you to set a token limit.
